### ISSUE TITLE
Enabling minify results in Error 500 mime no media type on all resources

### ISSUE THREAD

**Issue by martijndeb** [hacdias/caddy-minify#4] opened 2016-09-01 20:59 UTC
Using the latest caddy + minify addon on page load all resources minified are printing warnings on the console. HTML seems to be minified, other resources not.

[ERROR 500 /] mime: no media type

Config: just append minify to your config, no special declaration required.

**Comment by hacdias** [comment] 2016-09-01 21:18
The more interesting? I don't return a 500 Internal Server Error in the whole plugin. How can this be done? [Check it for yourself](https://github.com/hacdias/caddy-minify/blob/master/minify.go).

**Comment by martijndeb** [comment] 2016-09-02 04:29
Well removing the directive does clear up the error. Maybe something wholt should look at then?

**Comment by imjacobclark** [comment] 2016-09-04 19:30
Seeing the same problem. 

Caddy 0.9.1 (+e8e5595 Sun Sep 04 19:07:11 UTC 2016)

**Comment by hacdias** [comment] 2016-09-04 19:33
Hey all! Sorry for this, I can't figure out what the problem is! @mholt,
which is the revision that is on the server?

**Comment by mholt** [comment] 2016-09-05 04:05
Build server is currently building 1d4049b28a2bd1ec7aa52b01ce31f4e3a0ffc150 (and has been for some time).

```
$ git log
commit 1d4049b28a2bd1ec7aa52b01ce31f4e3a0ffc150
Author: Henrique Dias <hacdias@gmail.com>
Date:   Mon Aug 22 17:34:39 2016 +0100

    updates #3
```

Sorry about that, not sure what to tell you. Hope this was helpful!

**Comment by hacdias** [comment] 2016-09-05 07:48
This is really weird 'cause the error code I return is the code that was obtained by the others middleware ([see here](https://github.com/hacdias/caddy-minify/blob/master/minify.go#L33)).

One question: do it just log a 500 error, or it also sends a "500 Internal Server error" message to the browser? I'll try to check this out today ASAP.

**Comment by hacdias** [comment] 2016-09-05 07:55
I'm trying it out. Indeed, it returns an error, but not 500. It does return 200 with HTML/CSS and JS. I'm going to make some changes, but...

**Comment by hacdias** [comment] 2016-09-05 08:04
Hey!

@sexybiggetje @imjacobclark: I ask you to build it from source to check if it works well now. I think it does. :smile: Thanks :smiley:

**Comment by martijndeb** [comment] 2016-09-05 20:08
Works for me. Thanks for investigating!

**Comment by hacdias** [comment] 2016-09-06 13:30
I'll close this issue now :D

**Closed as completed by hacdias** 2016-09-06 13:30 UTC
Labels: bug
