### ISSUE TITLE
error when using minify with quic

### ISSUE THREAD

**Issue by SimJoSt** [hacdias/caddy-minify#22] opened 2018-03-06 17:13 UTC
I am using caddys experimental quic support.
When adding the `minify` directive, I get an:
> ERR_QUIC_PROTOCOL_ERROR

**Comment by hacdias** [comment] 2018-03-07 17:04
I'm trying to reproduce this issue but this is happening to me even if I don't add the `minify` directive.

**Comment by hacdias** [comment] 2020-07-17 18:34
Due to the recent developments of Caddy (v2!) and the incompatibility of this plugin with newer versions, as well as not being maintained, I'm closing this issue and archiving the repository.

**Closed as completed by hacdias** 2020-07-17 18:34 UTC
Labels: bug
