### ISSUE TITLE
minify in proxy mode

### ISSUE THREAD

**Issue by vteslia** [hacdias/caddy-minify#5] opened 2016-09-07 10:50 UTC
Hi,

did you perform tests with caddy in proxy mode? It seems if enable 'minification' caddy return "Content-Length: 0"

```
root@web:/opt/caddy# cat Caddyfile
178.62.201.147.xip.io:80 {
        proxy / xip.io
}
root@web:/opt/caddy# caddy -conf ./Caddyfile &
[1] 3114
root@web:/opt/caddy# Activating privacy features... done.
http://178.62.201.147.xip.io

root@web:/opt/caddy# curl -i http://178.62.201.147.xip.io/ 2>/dev/null |head -n 15
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Cache-Control: max-age=600
Content-Type: text/html; charset=utf-8
Date: Wed, 07 Sep 2016 10:47:38 GMT
Expires: Wed, 07 Sep 2016 10:57:38 GMT
Last-Modified: Tue, 28 Oct 2014 23:25:59 GMT
Server: Caddy
Server: GitHub.com
X-Github-Request-Id: B23EC993:89A8:356F89C:57CFF04A
Transfer-Encoding: chunked

<!doctype html>
<html>
  <!-- hello -->
root@web:/opt/caddy# kill $(pgrep caddy)
root@web:/opt/caddy#
[1]+  Done                    caddy -conf ./Caddyfile
root@web:/opt/caddy# vim Caddyfile
root@web:/opt/caddy# cat Caddyfile
178.62.201.147.xip.io:80 {
        proxy / xip.io
        minify
}
root@web:/opt/caddy# caddy -conf ./Caddyfile &
[1] 3128
root@web:/opt/caddy# Activating privacy features... done.
http://178.62.201.147.xip.io

root@web:/opt/caddy# curl -i http://178.62.201.147.xip.io/ 2>/dev/null |head -n 15
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Cache-Control: max-age=600
Content-Type: text/html; charset=utf-8
Date: Wed, 07 Sep 2016 10:48:38 GMT
Expires: Wed, 07 Sep 2016 10:58:38 GMT
Last-Modified: Tue, 28 Oct 2014 23:25:59 GMT
Server: Caddy
Server: GitHub.com
X-Github-Request-Id: B23EC993:89A6:1F7F9EA:57CFF086
Content-Length: 0

root@web:/opt/caddy#
```

Is it expected behaviour?

**Comment by hacdias** [comment] 2016-09-07 15:09
Hmm... Minify simply wraps the rest and it responds with the [length of the data](https://github.com/hacdias/caddy-minify/blob/master/minify.go#L71). Please, can you try building Caddy from source with minify to check if it works? I've made some changes that are not yet on caddyserver.com.

**Comment by vteslia** [comment] 2016-09-07 19:28
The same result on the freshest build:

```
root@web:/opt/caddy# caddy -version
Caddy 0.9.1 (+1ea96de Wed Sep 07 19:18:54 UTC 2016)
 1 file changed, 1 insertion(+)
caddyhttp/caddyhttp.go
root@web:/opt/caddy# caddy -plugins|grep minify
  http.minify
root@web:/opt/caddy#
root@web:/opt/caddy# cat Caddyfile
178.62.201.147.xip.io:80 {
        proxy / xip.io
        minify
}
root@web:/opt/caddy# caddy -conf ./Caddyfile &
[1] 24879
root@web:/opt/caddy# Activating privacy features... done.
http://178.62.201.147.xip.io

root@web:/opt/caddy# curl -i http://178.62.201.147.xip.io/
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Cache-Control: max-age=600
Content-Type: text/html; charset=utf-8
Date: Wed, 07 Sep 2016 19:24:12 GMT
Expires: Wed, 07 Sep 2016 19:34:12 GMT
Last-Modified: Tue, 28 Oct 2014 23:25:59 GMT
Server: Caddy
Server: GitHub.com
X-Github-Request-Id: B23EC993:89A6:21E03D0:57D0695C
Content-Length: 0

root@web:/opt/caddy#
```

Very strange.

**Comment by hacdias** [comment] 2016-09-10 15:35
@vteslia, I'm gonna check that!

**Comment by hacdias** [comment] 2016-09-10 20:13
@vteslia, I think I know where the problem is :)

**Comment by hacdias** [comment] 2016-09-10 20:15
Fixed ;) Rebuild it please and see the magic.

**Comment by vteslia** [comment] 2016-09-11 09:05
Hello,

`Content-Length: 0` issue is fixed but minification feature still doesn't work in proxy mode.

Look:

```
root@web:/opt/caddy# caddy -version
Caddy 0.9.1 (+1ea96de Sun Sep 11 08:27:10 UTC 2016)
 1 file changed, 1 insertion(+)
caddyhttp/caddyhttp.go
root@web:/opt/caddy# caddy -plugins|grep minify
  http.minify
root@web:/opt/caddy# cat Caddyfile
178.62.201.147.xip.io:80 {
        proxy / xip.io
        minify
}
root@web:/opt/caddy# caddy -conf ./Caddyfile &
[1] 2049
root@web:/opt/caddy# Activating privacy features... done.
http://178.62.201.147.xip.io

root@web:/opt/caddy# wget -q 178.62.201.147.xip.io -O with_minify_option.html
root@web:/opt/caddy# vim Caddyfile
root@web:/opt/caddy# kill $(pgrep caddy)
root@web:/opt/caddy# cat Caddyfile
178.62.201.147.xip.io:80 {
        proxy / xip.io
}
root@web:/opt/caddy# cat Caddyfile
178.62.201.147.xip.io:80 {
        proxy / xip.io
}
root@web:/opt/caddy# caddy -conf ./Caddyfile &
[1] 2081
root@web:/opt/caddy# Activating privacy features... done.
http://178.62.201.147.xip.io

root@web:/opt/caddy# wget -q 178.62.201.147.xip.io -O without_minify_option.html
root@web:/opt/caddy# wget -q xip.io -O original.html
root@web:/opt/caddy# ls -la
total 24
drwxr-xr-x 2 root root 4096 Sep 11 08:49 .
drwxr-xr-x 3 root root 4096 Sep  7 09:08 ..
-rw-r--r-- 1 root root   52 Sep 11 08:48 Caddyfile
-rw-r--r-- 1 root root 2869 Oct 28  2014 original.html
-rw-r--r-- 1 root root 2869 Oct 28  2014 with_minify_option.html
-rw-r--r-- 1 root root 2869 Oct 28  2014 without_minify_option.html
root@web:/opt/caddy#
root@web:/opt/caddy# md5sum ./*.html
2bd77a146ba16d73618d1ae2ec430373  ./original.html
2bd77a146ba16d73618d1ae2ec430373  ./with_minify_option.html
2bd77a146ba16d73618d1ae2ec430373  ./without_minify_option.html
root@web:/opt/caddy#
```

As you can see, there is no differences between origin page, through proxy and trough proxy with minify option.

It still perfectly minifies the same static page if it is located on disk:

```
root@web:/opt/caddy# cat Caddyfile
178.62.201.147.xip.io:80 {
        root /opt/caddy
        minify
}
root@web:/opt/caddy#
root@web:/opt/caddy# caddy -conf ./Caddyfile &
[1] 2225
root@web:/opt/caddy# Activating privacy features... done.
http://178.62.201.147.xip.io

root@web:/opt/caddy#
root@web:/opt/caddy#
root@web:/opt/caddy# wget -q 178.62.201.147.xip.io -O with_minify_without_proxy.html
root@web:/opt/caddy# ls -l
total 20
-rw-r--r-- 1 root root   61 Sep 11 08:59 Caddyfile
-rw-r--r-- 1 root root 2869 Oct 28  2014 index.html
-rw-r--r-- 1 root root 2869 Oct 28  2014 with_minify_option.html
-rw-r--r-- 1 root root 2601 Oct 28  2014 with_minify_without_proxy.html
-rw-r--r-- 1 root root 2869 Oct 28  2014 without_minify_option.html
root@web:/opt/caddy#
```

Any help will be very appreciated.

**Comment by hacdias** [comment] 2016-09-11 09:24
Hey @vteslia, sorry for that. Try now please.

**Comment by vteslia** [comment] 2016-09-11 09:40
Yeah! Now it works!

```
root@web:/opt/caddy# wget -q 178.62.201.147.xip.io -O with_minify_f517bd0.html
root@web:/opt/caddy# ls -l
total 24
-rw-r--r-- 1 root root   60 Sep 11 09:34 Caddyfile
-rw-r--r-- 1 root root 2869 Oct 28  2014 index.html
-rw-r--r-- 1 root root 2601 Oct 28  2014 with_minify_f517bd0.html
-rw-r--r-- 1 root root 2869 Oct 28  2014 with_minify_option.html
-rw-r--r-- 1 root root 2601 Oct 28  2014 with_minify_without_proxy.html
-rw-r--r-- 1 root root 2869 Oct 28  2014 without_minify_option.html
root@web:/opt/caddy# md5sum ./*.html
2bd77a146ba16d73618d1ae2ec430373  ./index.html
54d97aeb8a6f291ccd9bec298a89dadf  ./with_minify_f517bd0.html
2bd77a146ba16d73618d1ae2ec430373  ./with_minify_option.html
54d97aeb8a6f291ccd9bec298a89dadf  ./with_minify_without_proxy.html
2bd77a146ba16d73618d1ae2ec430373  ./without_minify_option.html
root@web:/opt/caddy#
```

Thank you so much!

**Comment by hacdias** [comment] 2016-09-11 09:46
Awesome! Gonna close this now 😄 Thank you for reporting this.

**Comment by hacdias** [comment] 2016-09-11 09:47
_Ping @mholt: I ask you to update this on the server when you've got 10 mins 😃_

**Closed as completed by hacdias** 2016-09-11 09:46 UTC

**Comment by mholt** [comment] 2016-09-13 00:09
K, I'll try to do that this week.

**Comment by hacdias** [comment] 2016-09-13 06:17
Thanks! :)

**Comment by mholt** [comment] 2016-09-20 22:25
All done, will be available in a few moments.

**Comment by hacdias** [comment] 2016-09-20 22:32
Thanks! :)

**Comment by hacdias** [comment] 2016-09-20 22:32
@mholt: any news about the update of the docs?

**Comment by mholt** [comment] 2016-09-20 22:38
If they've been pushed to master at the caddyserver.com repo, then they'll be deployed today!

**Comment by hacdias** [comment] 2016-09-21 06:17
Thanks! :)
